### ISSUE TITLE
SEO enhancements | Sitemap

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/American-Studies#10]
Use a sitemap to indicate preferred URLs for the same content
Pick a canonical (preferred) URL for each of your pages, and tell us about your preference by submitting these canonical URLs in a sitemap.

We don't guarantee that we'll use the URLs you submit in a sitemap, but submitting one is a useful way to tell Google about the pages on your site you consider most important.

![screen shot 2017-04-27 at 10 10 24 am](https://cloud.githubusercontent.com/assets/12816361/25496582/792cd74c-2b4f-11e7-8911-203c13686dce.png)

**Comment by pixelyunicorn** [comment]
http://develop.cla.temple.edu/american-studies/sitemap.xml should generate a proper sitemap now. Since Jekyll is not aware of what URL the site is being pushed to, I added a field at the top of _config.yml containing the field for the final production site URL. Should I make this change to all the sites?

**Comment by tu-chill** [comment]
@LabLayers yes! can we add this to all our programs.

**Comment by CVE82** [comment]
I have added the sitemap file into all program repos.
